---
title: "Posts & Files & Varia"

output:
  html_document:
    df_print: paged
---

<!--### Content:-->

#### Stylometry, Saga Corpus & Egils saga

-   [Saga Corpus](https://clarin.is/en/resources/sagacorpus/): Link to the data-set (by Eiríkur Rögnvaldsson & Sigrún Helgadóttir, 2011/2022) at Clarin-IS. If the download issue has not been resolved yet, see: [repository.clarin.is](http:/hdl.handle.net/20.500.12537/32).

-   [Saga Corpus MDS 3-in-1](content/egla/Saga_Corpus_MDS_3in1.html): Saga Corpus 1-, 2-, 3-gram 1000 MFW/MFF visualized with Multidimensional Scaling. Interactive plotly plot.

-   [Video](content/egla/MFW_TEST_PNG_LIMITED_VIDEO.mp4): 10-1000 MFW/MFF centered around 5 sagas from SC in order to hypothesize about the influence of the size of the features on authorship conjectures. Using Multidimensional Scaling for dimension reduction.

-   [Video](content/egla/MFW_ALL_PNG_VIDEO.mp4): Same as above, but includes all texts.

-   Different plots based on Burrows' Delta distance measures(in PDFs):

    -   All of the bellow and some more: [All-in-one](content/egla/Snippet_from_BA_Egils_Saga_Czindrity.pdf)
    -   PCA 1000 MFW/MFF:
        -   [PCA 1-gram](content/egla/plots/Saga_Corpus_PCA_1gram_1000MFW.pdf) & [PCA 1-gram plotly](content/egla/plotly/Saga_Corpus_PCA_1Gram.html)
        -   [PCA 2-gram](content/egla/plots/Saga_Corpus_PCA_2gram_1000MFW.pdf) & [PCA 2-gram plotly](content/egla/plotly/Saga_Corpus_PCA_2Gram.html)
        -   [PCA 3-gram](content/egla/plots/Saga_Corpus_PCA_3gram_1000MFW.pdf) & [PCA 3-gram plotly](content/egla/plotly/Saga_Corpus_PCA_3Gram.html)
    -   Multidimensional Scaling 1000 MFW/MFF:
        -   [MDS 1-gram](content/egla/plots/Saga_Corpus_mds_1gram_1000MFW.pdf) & [MDS 1-gram plotly](content/egla/plotly/Saga_Corpus_MDS_1Gram.html)
        -   [MDS 2-gram](content/egla/plots/Saga_Corpus_mds_2gram_1000MFW.pdf) & [MDS 2-gram plotly](content/egla/plotly/Saga_Corpus_MDS_2Gram.html)
        -   [MDS 3-gram](content/egla/plots/Saga_Corpus_mds_3gram_1000MFW.pdf) & [MDS 3-gram plotly](content/egla/plotly/Saga_Corpus_MDS_3Gram.html)
    -   Hierarchical Clusters 1000 MFW/MFF:
        -   [HCA 1-gram](content/egla/plots/Saga_Corpus_cluster_1gram_1000MFW.pdf)
        -   [HCA 2-gram](content/egla/plots/Saga_Corpus_cluster_2gram_1000MFW.pdf)
        -   [HCA 3-gram](content/egla/plots/Saga_Corpus_cluster_3gram_1000MFW.pdf)

#### Varia

-   [HJB](https://nkcz.github.io/content/hjb/about.html) - Showcase for a static and easy implementation of a possible digital edition of *Hjertebogen*. The implementation is based on R-markdown and uses the R-package flexdashboard for the sake of layout and style.

-   My Rosalind profile: [NKCZ at Rosalind](https://rosalind.info/users/nkcz/).
